# Generated by Django 5.2.7 on 2025-10-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição"
            ),
        ),
    ]
