# Generated by Django 5.2.7 on 2025-10-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "curso", "verbose_name_plural": "cursos"},
        ),
        migrations.AddField(
            model_name="course",
            name="situation",
            field=models.BooleanField(default=True, verbose_name="Situação"),
        ),
    ]
