# Generated by Django 5.2.7 on 2025-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_options_course_situation"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
