# Generated by Django 5.2.7 on 2025-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "situation",
                    models.BooleanField(default=True, verbose_name="Situação"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Edição"
                    ),
                ),
            ],
            options={
                "verbose_name": "sobre",
                "verbose_name_plural": "sobre",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
